version: '3.8'

services:

  api:
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
      qdrant:
        condition: service_started
      ollama:
        condition: service_healthy  # Ensure ollama is healthy before starting
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    command: ["bash", "-c", "dbmate up && python -m uvicorn --host 0.0.0.0 --reload app.main:app"]
    env_file:
      - .env


  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    healthcheck:
      test: "bash -c 'cat < /dev/null > /dev/tcp/localhost/11434'"
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: postgres:15-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: application
    ports:
      - "5432:5432"


volumes:
  pg-data:
    driver: local
